#
title: Eric Hogue's Blog
email: blog@erichogue.ca
description: >- # this means to ignore newlines until "baseurl:"
  Writting about web development, security and anything that interest me.¬

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://erichogue.ca" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Eric Hogue
author-img: EricHogue.jpg
about-author: 
  I am a web developer from Montreal, Quebec, Canada. I write about web development 
  , security and anything that interest me.

social-twitter: ehogue
social-github: EricHogue
social-linkedin: ehogue
social-email: blog@erichogue.ca
social-stackexchange: 2919
#* [Stack Overflow Career](http://careers.stackoverflow.com/erichogue)


#twitter_username: ehogue
#github_username:  EricHogue
#linkedin_username: ehogue

show_excerpts: true
permalink: /:title/


# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from


# Disqus
discus-identifier: erichogue

# Tracker
analytics: UA-20604950-1

# Build Settings
#markdown: kramdown

paginate: 8
paginate_path: "/page/:num"

include:
  - .well-known
